use_frameworks!

platform :ios, '8.0'

target 'YLBScrollViewNest_Example' do
  pod 'YLBScrollViewNest', :path => '../'

  target 'YLBScrollViewNest_Tests' do
    inherit! :search_paths

    
  end
end
