#use_frameworks!

platform :ios, '9.0'

target 'YLBScrollViewNest_Example' do
  pod 'YLBScrollViewNest', :path => '../'
  
  # 基础库
  pod 'YLBCommon', :git =>'https://github.com/ProBobo/YLBCommon.git'
  
  #开源库
  pod 'MJRefresh'
  pod 'MBProgressHUD','0.9.2'

  target 'YLBScrollViewNest_Tests' do
    inherit! :search_paths

    
  end
end
